package com.ibmec.remomeurumo.dto;

public enum TipoOperacaoConfirmacao {
    CRIAR_PARTICIPANTE,
    EDITAR_PARTICIPANTE,
    ATIVAR_PARTICIPANTE,
    DESATIVAR_PARTICIPANTE,
    EXCLUIR_PARTICIPANTE,
    CRIAR_ATIVIDADE,
    EDITAR_ATIVIDADE,
    ATIVAR_ATIVIDADE,
    DESATIVAR_ATIVIDADE,
    EXCLUIR_ATIVIDADE,
    CRIAR_ENCONTRO,
    EDITAR_ENCONTRO,
    CANCELAR_ENCONTRO,
    EXCLUIR_ENCONTRO,
    REGISTRAR_PRESENCA,
    EXCLUIR_PRESENCA
}
